embedding_size: 64
feat_embed_dim: 64

n_layers: [2]
dropout: [0.3]
reg_weight: [0.01]
cl_weight: 2.0

use_neg_sampling: False

gated_fusion: True
multimodal_gcn: True
mlp_predictor: True
separate_predictors: True
mlp_features: True

hyper_parameters: ["n_layers", "reg_weight", "dropout"]

epochs: 200