embedding_size: 128
feat_embed_dim: 128
weight_size: [128, 128]

learning_rate: 0.001
lambda_coeff: 0.9
reg_weight: [0.001]
reg_weight_l2: [0.0001]
cl_weight: [0.1]

n_mm_layers: 1
n_ui_layers: [2]
knn_k: 10

mm_image_weight: 0.5
dropout: [0.4]
mm_edge_dropout: [0.2]

mlp_features: True
gated_fusion: True
dynamic_attention: True
residual_gcn: True
rebuild_mm_adj: True

hyper_parameters: ["n_ui_layers", "reg_weight", "reg_weight_l2", "cl_weight", "dropout", "mm_edge_dropout"]

epochs: 600